spring:
  security:
    user:
      name: proyectouser
      password: pass1234
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  h2:
    console:
      enabled: true
      path: /h2-console
  # Configuración de JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
# Puerto del servidor
server:
  port: 8090
  servlet:
    context-path: /proyectofinal
logging:
  level:
    com:
      exacom:
        proyectofinal: debug
